FactoryGirl.define do
  factory :title do
    imdb_id "MyString"
    title "MyString"
    year "MyString"
    rated "MyString"
    released "MyString"
    runtime "MyString"
    genre "MyString"
    director "MyString"
    writers "MyString"
    actors "MyString"
    plot "MyString"
    country "MyString"
    language "MyString"
    metascore "MyString"
    poster "MyString"
    rating "MyString"
    votes "MyString"
    budget "MyString"
    opening_weekend "MyString"
    gross "MyString"
    production "MyString"
    parent_id "MyString"
    type ""
    session "MyString"
    episode "MyString"
    status "MyString"
  end
end
